notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

dist: trusty

language: c

install: true

compiler:
  - gcc

install:
  - wget https://sourceforge.net/projects/linasm/files/linasm-1.13%28stable%29.tar.gz/download -O linasm.tar.gz 
  - tar -xzf linasm.tar.gz
  - ls ./
  - pushd linasm-1.13\(stable\) && make && sudo make install && popd

script:
  - ./setup.sh ~/wtsi-opt
