notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

dist: trusty

language: c

install: true

compiler:
  - gcc

before_script:
  - wget https://sourceforge.net/projects/linasm/files/linasm-1.13%28stable%29.tar.gz/download -O /tmp/linasm.tar.gz 
  - mkdir /tmp/linasm
  - tar --strip-components 1 -C /tmp/linasm -xzf /tmp/linasm.tar.gz
  - cd /tmp/linasm
  - make
  - sudo make install

script:
  - ./setup.sh ~/wtsi-opt
